[buildPlans.Izosevka]
family = "Izosevka"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Izosevka.variants]
  inherits = "ss14"

    [buildPlans.Izosevka.variants.design]
    zero = "slashed"
    a = "single-storey-earless-corner-tailed"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    g = "single-storey-earless-corner"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "earless-corner-serifless"
    cyrl-a = "single-storey-earless-corner-tailed"
    cyrl-er = "earless-corner-serifless"

[buildPlans.Izosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Izosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Izosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Izosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
